import remarkDirective from "remark-directive"
import { visit } from "unist-util-visit"
import { QuartzTransformerPlugin } from "../types"
import { Node } from "unist"

// 1. Remark Plugin: Just creates the grid wrapper, leaves children alone for Quartz to parse
const remarkGallery = () => {
  return (tree: Node) => {
    visit(tree, "containerDirective", (node: any) => {
      if (node.name !== "gallery") return
      
      const data = node.data || (node.data = {})
      data.hName = "div"
      // Note: rehype expects className as an array
      data.hProperties = { className: ["gallery-grid"] } 
    })
  }
}

// 2. Rehype Plugin: Runs after Quartz has turned wikilinks into actual HTML <img> tags
const rehypeGallery = () => {
  return (tree: Node) => {
    visit(tree, "element", (node: any) => {
      // Find our gallery grid container
      if (node.tagName === "div" && node.properties?.className?.includes("gallery-grid")) {
        const figures: any[] = []
        
        // Dig through the container and extract ALL generated <img> tags
        visit(node, "element", (imgNode: any) => {
          if (imgNode.tagName === "img") {
            const altText = imgNode.properties?.alt || ""
            
            figures.push({
              type: "element",
              tagName: "figure",
              properties: { className: ["gallery-item"] },
              children: [
                imgNode, // Keep the original image node generated by Quartz
                {
                  type: "element",
                  tagName: "figcaption",
                  properties: { className: ["gallery-caption"] },
                  children: [{ type: "text", value: altText }]
                }
              ]
            })
          }
        })
        
        // Replace the grid's children entirely with our new <figure> elements
        node.children = figures
        return "skip" // Prevents the visitor from infinitely looping through the new children
      }
    })
  }
}

export const Gallery: QuartzTransformerPlugin = () => {
  return {
    name: "Gallery",
    markdownPlugins() {
      return [remarkDirective, remarkGallery]
    },
    htmlPlugins() {
      // Inject our rehype plugin into the HTML phase
      return [rehypeGallery] 
    },
  }
}
